# Generated by Django 4.1.2 on 2022-12-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="commision",
            new_name="commission",
        ),
    ]
