# Generated by Django 4.1.2 on 2022-12-06 10:12

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_uid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=16,
                max_length=16,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
