# Generated by Django 4.1.2 on 2022-12-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_commision_transaction_commission"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="transaction",
            table="transactions",
        ),
    ]
