# Generated by Django 4.1.2 on 2022-12-07 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "uid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=8,
                        max_length=8,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[("VISA", 1), ("MasterCard", 2)],
                        default="VISA",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", 1), ("USD", 2), ("EUR", 3)], max_length=3
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
