# Generated by Django 4.1.2 on 2022-12-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="card_type",
            field=models.CharField(
                choices=[("VISA", 1), ("Mastercard", 2)], default="VISA", max_length=20
            ),
        ),
    ]
