# Generated by Django 4.1.2 on 2022-12-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0002_rename_owner_id_wallet_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="balance",
        ),
        migrations.AddField(
            model_name="wallet",
            name="alien_balance",
            field=models.DecimalField(decimal_places=2, default=3, max_digits=20),
        ),
        migrations.AddField(
            model_name="wallet",
            name="rub_balance",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
    ]
