# Generated by Django 4.1.2 on 2022-12-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0003_remove_wallet_balance_wallet_alien_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="alien_balance",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="rub_balance",
        ),
        migrations.AddField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[("RUB", 100), ("USD", 3), ("EUR", 3)],
                default="RUB",
                max_length=3,
            ),
        ),
    ]
