# Generated by Django 4.1.2 on 2022-12-05 09:57

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0004_remove_wallet_alien_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[("RUB", 1), ("USD", 2), ("EUR", 3)], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="uid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=8,
                max_length=8,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
