# Generated by Django 4.1.2 on 2022-12-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0005_alter_wallet_currency_alter_wallet_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="card_type",
            field=models.IntegerField(
                choices=[("VISA", 1), ("MasterCard", 2)], default="VISA"
            ),
        ),
    ]
