# Generated by Django 4.1.2 on 2022-12-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0006_alter_wallet_card_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="card_type",
            field=models.CharField(
                choices=[("VISA", 1), ("MasterCard", 2)], default="VISA", max_length=20
            ),
        ),
    ]
