# Generated by Django 4.1.2 on 2022-12-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="id",
            new_name="user_id",
        ),
    ]
