# Generated by Django 4.1.2 on 2022-12-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_id_customuser_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_id",
            new_name="id",
        ),
    ]
