# Generated by Django 4.1.2 on 2022-12-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_wallets_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="accounts",
        ),
    ]
